version: '3.8'

services:
  kompani:
    image: ghcr.io/danielpereod/kompani:master
    container_name: kompani
    ports:
      - "3000:3000"
    volumes:
      - ./books:/books
    environment:
      - BOOKS_DIR=/books
    restart: unless-stopped
